### PR TITLE
Disable Quad & Squad rooms due to low usage

### PR DESCRIPTION
**Pull request by j3camero**
This vote will also be taken as representative for #commands and other rooms hidden due to low usage.

### CODE REVIEW

**Comment by Bagdadcowboy** [comment]
Im dumb this page is messy for my brain, not ADHD friendly.

I vote "Wipe" text & voice Channels stay and 
also i like the option to keep bot to spawn new channels and remove them once the last participant in VC leaves.

**Comment by Koof91** [comment]
I'm not a big fan of removing the rank channel and the wipe channel.. 
Wipe channel has been inactive due to lack of inactivity this wipe..

**Comment by Scarrab** [comment]
the wipe text channel has been restored; I think the ranks channel should stay gone...it encourages addiction and...other maladaptive behaviors

**Comment by j3camero** [comment]
> I vote "Wipe" text & voice Channels stay

Wipe text channel restored. Can we compromise on the VC as it truly had exactly zero usage, even during emergencies. And we've had emergencies. Those arguing that they need it to hide from rampant spies had months to try using it even a single time and they themselves didn't. We agreed on these rooms as an experiment almost a year ago and we said we'd all look to the traffic in the Wipe VC room to assess later. Everyone agreed on that at the time. Those afraid of spies claimed that everyone would always be in the Wipe room since Main is completely unsuitable due to spies. Those unafraid of spies predicted that the Wipe rooms would get less usage than Main. The reality is that one side of the bet turned out to validated and the other not. We all agreed on the criteria for settling this matter in advance. At this time, those on the afraid-of-spies side of the debate lack credibility since we already tried their thing and they themselves never used and them themselves committed to falsifiable predictions, certain they would be validated, but turned out not to be. No hard feelings, that's how we settle such bets professionally and without hard feelings. Those that refuse to abide by the pre-agreed criteria show they have little credibility. This all started with us asking them what it would take for them to agree they're wrong, and now the data is the data. Anyone arguing that we're absolutely hosed without a spy-proof Wipe VC isn't credible at this point.

> also i like the option to keep bot to spawn new channels and remove them once the last participant in VC leaves.

That will still work. No change there.

**Comment by Bagdadcowboy** [comment]
Following what Jeff wrote in here.

I vote "Wipe" Text channel and "rank" channel stay. Voice chats i agree been little to no use.,

**Pull request merged**
