### PR TITLE
Urgent Security Fix

### PR DESCRIPTION
**Pull request by j3camero**
Last night Aperture (donatarigov) force-merged a code change, bypassing the vote-based system. This is the equivalent of Jeff right-click banning someone in Discord before their trial in Ban Court has completed, bypassing the voters.

This is his 2nd offense. The first time he did it I explained to him that even though he has admin access to the repo and can therefore force-merge any PR bypassing the voters, that this is a loophole and should not be done. This rules out that he somehow didn't know or realize. He knows damn well. None of the other voters have ever done this. They all know better. So does Aperture.

He did it in the dead of night, at 2:30 AM Eastern.

He himself was part of the original voters who agreed on a 24h minimum time to pass any code change. The time limit is enforced automatically by a GitHub Action that we installed called "democracy". Aperture abused his admin powers to bypass this system.

One of the first things we did after the vote-based system was installed was to set the 24h minimum. It stops people from passing a PR in the middle of the night. It creates a relaxed non-tactical atmosphere where voters get that guaranteed 24h to consider their vote, change their mind, suggest changes, etc. Just like the minimum timer in Ban Court. It stops 3 voters from banning someone in the dead of night.

Question: "could this have been a mistake? Maybe he unknowingly slipped up"
Answer: unfortunately it's not possible. When the automated checks including the vote system are all in a passing state, the Merge button turns bright green and gets larger. It's extremely salient. To bypass the voting system, he had had to click a small greyed out Merge button with a red X near it. He then had to click through a secondary warning that warns him the checks haven't passed yet. There's no possibility this was an accident.

Question: is this just pedantic rule enforcement? Does this actually matter?
Answer: Yes! The problem with someone who shows they won't respect the 24h minimum is he could pass a change that adds discord.delete() in the dead of night. 10 seconds later the change would be auto-deployed and the entire discord would be permanently deleted forever. By the time other voters got up in the morning to vote against the change, it would be too late. This is therefore an URGENT security matter.

### CODE REVIEW

**Comment by j3camero** [comment]
FYI here is what it looks like when you pass the vote-based system. Huge green button. Lots of green check marks. Absolutely unmistakable. This screen is the same across all companies so professional coders are extensively familiar with this. Even when a coder moves between companies, this screen stays the same at both companies. Any professional coder would be extensively familiar with this screen, and especially in Aperture's case I know he is.

image

He would have known without any doubt or possibility of error, that if you don't see all this green stuff then you don't merge the PR. At a company, such behavior of repeatedly jamming code changes through without review (ie: no green button) would result in that employee being FIRED.

**Comment by donatarigov** [comment]
This is entirely false as the button shouldn't appear until all checks have passed. So perhaps we need to look into ensuring the button doesn't appear until then. I don't have any super admin power. This is something that needs to be fixed in the repository settings as anyone could do this. 

It was late last night and I saw the 4 votes yes and the green button appeared (it didn't earlier when I opened the PR). My bad I didn't notice and we can correct this issue. 

Additionally not sure how adding a general to the voters is in anyway malicious.

**Comment by j3camero** [comment]
Liar. The button was not green. Aperture knows damn well how it works, so you can all be sure that he is deliberately lying to you.

Here is what he would have seen. Big red warning. Greyed out button.

image

After he clicked Merge he would have had to pass through a second warning that looks like this:

image

There's NO WAY he could have mistaken this for the "big green button" that all professional coders know. This was definitely a deliberate, conscious decision that he made. Non-coders be assured that no pro coder could possibly make this mistake innocently. If he did this at a job he would be written up and then if it happened again he would be fired. And he knows that damn well.

**Comment by donatarigov** [comment]
> Liar. The button was not green. Aperture knows damn well how it works, so you can all be sure that he is deliberately lying to you.
> 
> Here is what he would have seen. Big red warning. Greyed out button.
> 
> image
> 
> After he clicked Merge he would have had to pass through a second warning that looks like this:
> 
> image
> 
> There's NO WAY he could have mistaken this for the "big green button" that all professional coders know. This was definitely a deliberate, conscious decision that he made. Non-coders be assured that no pro coder could possibly make this mistake innocently. If he did this at a job he would be written up and then if it happened again he would be fired. And he knows that damn well.

Actually I'm not the liar here. Now your attacking my character Jeff hypocrite much? 

I don't even have the grey option as shown in my screenshot. I don't have any buttons.

**Comment by donatarigov** [comment]
image

Another new screenshot for proof of this.

**Comment by j3camero** [comment]
This turned into an embarrassing failure. The people voting No tell me they want to vote Yes but it's not worth it due to social incentives. Their incentive is to sit on the fence because they know that if they don't do anything, I will have to step in as the repo owner to fix it. So why expose themselves to criticism for taking a tough Yes vote?

That is a genuinely tough problem. Something to consider for the future. For now though, it's clear that this person abused their powers not once, but twice, leaving no doubt as to it being intentional. Code democracy has somewhat failed as an experiment for now. Everyone expects me to act.

**Pull request merged**
